import {
  createSavedChart,
  deleteSavedChart,
  deleteTemplate as deleteTemplateRequest,
  discoverReports,
  editTemplateAi,
  editTemplateManual,
  exportTemplateZip,
  fetchTemplateKeyOptions,
  getTemplateCatalog,
  getTemplateHtml,
  importTemplateZip,
  isMock,
  listApprovedTemplates,
  listSavedCharts,
  recommendTemplates,
  runReportAsJob,
  suggestCharts,
  undoTemplateEdit,
  updateSavedChart,
  withBase,
} from '../../../api/client'
import * as mock from '../../../api/mock'

export {
  createSavedChart,
  deleteSavedChart,
  deleteTemplateRequest,
  discoverReports,
  editTemplateAi,
  editTemplateManual,
  exportTemplateZip,
  fetchTemplateKeyOptions,
  getTemplateCatalog,
  getTemplateHtml,
  importTemplateZip,
  isMock,
  listApprovedTemplates,
  listSavedCharts,
  mock,
  recommendTemplates,
  runReportAsJob,
  suggestCharts,
  undoTemplateEdit,
  updateSavedChart,
  withBase,
}
